version: '2.2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - 'docker-config.env'

  redis:
    image: 'redis:3.2-alpine'
    volumes:
      - 'redis:/data'

  memcached:
    image: 'memcached:alpine'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'memcached'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/isk'
    env_file:
      - 'docker-config.env'
    command: 'bundle exec rails s -b 0.0.0.0'
    init: true

  worker:
    depends_on:
      - 'website'
    image: 'isk_website'
    volumes:
      - '.:/isk'
    env_file:
      - 'docker-config.env'
    command: './script/background_jobs.rb run'
    init: true

  resque:
    depends_on:
      - 'website'
    image: 'isk_website'
    volumes:
      - '.:/isk'
    env_file:
      - 'docker-config.env'
    environment:
      - QUEUE=*
    command: 'bundler exec rake resque:work --trace'
    init: true

  proxy:
    image: 'nginx:alpine'
    depends_on:
      - 'website'
    ports:
      - '8080:80'
    volumes:
      - '.:/isk'
      - './docker-nginx.conf:/etc/nginx/conf.d/default.conf:ro'



volumes:
  redis:
  postgres:
